[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
deadpool-postgres = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = "0.7.10"
